Revert "giflib: update to 6.1.2"
This reverts commit f36453d736bea6a69e2a0b87a60ae9631ccaff2e.

giflib 6.1.2 breaks building TexturePacker:
.../tools/depends/native/TexturePacker/src/decoder/GifHelper.cpp:58:17: error: too few arguments to function 'GifFileType* DGifOpen(void*, InputFunc, int*)'
   58 |   gif = DGifOpen(dataPtr, readFunc);
      |         ~~~~~~~~^~~~~~~~~~~~~~~~~~~